import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/utils/theme";
import { Providers } from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const monteserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Exam Interview",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={monteserrat.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <ToastContainer />
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
